apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubrain
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: platform
    repoURL: oci://${REGISTRY_URL}/${ORG_NAME}/kuberse/helm/platform
    targetRevision: ${PLATFORM_VERSION}
    helm:
      values: |
        kubrain:
          enabled: true
          image:
            repository: ${REGISTRY_URL}/${ORG_NAME}/kuberse/img/kubrain
            pullPolicy: IfNotPresent
          configFile:
            enabled: true
            content: |
              database:
                url: env.PG_CONNECTION_STRING
                synchronize: true
              ingestion:
                github:
                  owner: ${ORG_NAME}
                  match: "**/kuberse-entity.yaml"
                  fetch: "*/5 * * * *"
                  token: env.GITHUB_TOKEN
                gitea:
                  url: env.GITEA_URL
                  owner: ${ORG_NAME}
                  match: "**/kuberse-entity.yaml"
                  fetch: "*/5 * * * *"
                  token: env.GITEA_TOKEN
              argocd:
                url: https://argocd-server.argocd.svc.cluster.local
                insecure: true
                username: env.ARGOCD_USERNAME
                password: env.ARGOCD_PASSWORD
              vault:
                url: env.VAULT_URL
                token: env.VAULT_TOKEN
              buildapp:
                chartRepo: oci://${REGISTRY_URL}/${ORG_NAME}/kuberse/helm/buildapp
                chartVersion: latest
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
