apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runners
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: runners
    repoURL: oci://${REGISTRY_URL}/${ORG_NAME}/kuberse/helm/runners
    targetRevision: ${RUNNERS_VERSION}
    helm:
      values: |
        arc-runners:
          enabled: true
          template:
            spec:
              containers:
                - name: runner
                  image: ${REGISTRY_URL}/${ORG_NAME}/kuberse/img/kuberse-runner:latest
                  imagePullPolicy: IfNotPresent
  destination:
    server: https://kubernetes.default.svc
    namespace: runners
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
